// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
///  );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv1DeT2G4MAvKas_FZK2qY_IgS9ngKrEo',
    appId: '1:410029319860:web:b0534ed12ad3ff22ed19e1',
    messagingSenderId: '410029319860',
    projectId: 'paises-del-mundo-70d24',
    authDomain: 'paises-del-mundo-70d24.firebaseapp.com',
    storageBucket: 'paises-del-mundo-70d24.firebasestorage.app',
    measurementId: 'G-D25BZZF3PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHIcJyvo4Bciv9X0LyksU96qqonRzxUh0',
    appId: '1:410029319860:android:cfdbfc9780f1dfd4ed19e1',
    messagingSenderId: '410029319860',
    projectId: 'paises-del-mundo-70d24',
    storageBucket: 'paises-del-mundo-70d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn3lM_lT0-4myN8kTic2CXCDvXA24NqPg',
    appId: '1:410029319860:ios:92532aacf1530e35ed19e1',
    messagingSenderId: '410029319860',
    projectId: 'paises-del-mundo-70d24',
    storageBucket: 'paises-del-mundo-70d24.firebasestorage.app',
    iosBundleId: 'com.example.tpFinCuatrimestre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn3lM_lT0-4myN8kTic2CXCDvXA24NqPg',
    appId: '1:410029319860:ios:92532aacf1530e35ed19e1',
    messagingSenderId: '410029319860',
    projectId: 'paises-del-mundo-70d24',
    storageBucket: 'paises-del-mundo-70d24.firebasestorage.app',
    iosBundleId: 'com.example.tpFinCuatrimestre',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv1DeT2G4MAvKas_FZK2qY_IgS9ngKrEo',
    appId: '1:410029319860:web:e3c79f8bc81111c5ed19e1',
    messagingSenderId: '410029319860',
    projectId: 'paises-del-mundo-70d24',
    authDomain: 'paises-del-mundo-70d24.firebaseapp.com',
    storageBucket: 'paises-del-mundo-70d24.firebasestorage.app',
    measurementId: 'G-DKWPP7JMZT',
  );
}
